### ISSUE TITLE
Failed building wheel for httptools

### ISSUE THREAD

**Issue by RoConverse** [MagicStack/httptools#35] opened 2019-05-05 07:47 UTC
While installing the module i get the following error

```
Collecting httptools
  Using cached https://files.pythonhosted.org/packages/1b/03/215969db11abe8741e9c266a4cbe803a372bd86dd35fa0084c4df6d4bd00/httptools-0.0.13.tar.gz
Building wheels for collected packages: httptools
  Building wheel for httptools (setup.py) ... error
  Complete output from command c:\python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\MOHAMM~1\\AppData\\Local\\Temp\\pip-install-3uy2x1yx\\httptools\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\MOHAMM~1\AppData\Local\Temp\pip-wheel-ha0o16_d --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\httptools
  copying httptools\__init__.py -> build\lib.win-amd64-3.6\httptools
  creating build\lib.win-amd64-3.6\httptools\parser
  copying httptools\parser\errors.py -> build\lib.win-amd64-3.6\httptools\parser
  copying httptools\parser\__init__.py -> build\lib.win-amd64-3.6\httptools\parser
  running egg_info
  writing httptools.egg-info\PKG-INFO
  writing dependency_links to httptools.egg-info\dependency_links.txt
  writing top-level names to httptools.egg-info\top_level.txt
  reading manifest file 'httptools.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'httptools.egg-info\SOURCES.txt'
  copying httptools\parser\parser.c -> build\lib.win-amd64-3.6\httptools\parser
  running build_ext
  building 'httptools.parser.parser' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

  ----------------------------------------
  Failed building wheel for httptools
  Running setup.py clean for httptools
Failed to build httptools
Installing collected packages: httptools
  Running setup.py install for httptools ... error
    Complete output from command c:\python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\MOHAMM~1\\AppData\\Local\\Temp\\pip-install-3uy2x1yx\\httptools\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\MOHAMM~1\AppData\Local\Temp\pip-record-schzesxc\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\httptools
    copying httptools\__init__.py -> build\lib.win-amd64-3.6\httptools
    creating build\lib.win-amd64-3.6\httptools\parser
    copying httptools\parser\errors.py -> build\lib.win-amd64-3.6\httptools\parser
    copying httptools\parser\__init__.py -> build\lib.win-amd64-3.6\httptools\parser
    running egg_info
    writing httptools.egg-info\PKG-INFO
    writing dependency_links to httptools.egg-info\dependency_links.txt
    writing top-level names to httptools.egg-info\top_level.txt
    reading manifest file 'httptools.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'httptools.egg-info\SOURCES.txt'
    copying httptools\parser\parser.c -> build\lib.win-amd64-3.6\httptools\parser
    running build_ext
    building 'httptools.parser.parser' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

```
I am on windows and I have installed Visual C++ Build Tools. But the problem isnt resolved yet

**Comment by tedder** [comment] 2019-06-24 23:07
dupe of #33

**Comment by Grasshooper** [comment] 2019-07-13 12:30
@tedder  please check the problem : #33  is for Linux and the question here is for windows.

**Comment by elprans** [comment] 2020-02-06 00:36
Wheels are now available.

**Closed by elprans** 2020-02-06 00:36 UTC
