### ISSUE TITLE
new nodejs parser: llhttp

### ISSUE THREAD

**Issue by Skorpeo** [MagicStack/httptools#31] opened 2019-01-21 12:53 UTC
New node js parser: https://github.com/nodejs/http-parser/pull/285#issuecomment-456025694

**Comment by victoraugustolls** [comment] 2020-10-13 21:16
Hey @elprans ! Do you have an opinion about moving to `llhttp`? As `http-parser` is no longer maintained :(

**Comment by elprans** [comment] 2020-10-13 22:49
We don't really have the bandwidth to make the switch, but if anyone wants to pick this up, patches are welcome!

**Comment by victoraugustolls** [comment] 2020-10-20 21:03
Hi @elprans ! I'm trying to take this one here: https://github.com/victoraugustolls/httptools

I'm having some trouble with the tests due to some missing exceptions between `http-parser` and `llhttp`. Could you help me? Or point me someone to help?

The problem is that there are no callback errors for `on_body`, `on_header`, `on_url` and `on_status`. Other point is that I had to change how the upgrade works, but don't know if this is correct.

Maybe @indutny can help also? (sorry if tagging you here is wrong)

**Comment by indutny** [comment] 2020-10-22 17:41
@victoraugustolls I'd be happy to help!

You basically need to do what Node.js does at this moment if you'd like to raise an error from the on_body/etc callbacks:
```c
      llhttp_set_error_reason(&parser_, "HPE_JS_EXCEPTION:JS Exception");
      return HPE_USER;
```

**Comment by victoraugustolls** [comment] 2020-10-23 01:46
Perfect! Thanks @indutny ! Will give it a go over the weekend!

**Comment by abersheeran** [comment] 2020-12-09 03:10
Is there any progress?

**Comment by victoraugustolls** [comment] 2020-12-09 15:26
Hey @abersheeran ! There is an open PR for it: #56

**Comment by 1st1** [comment] 2020-12-09 21:15
We've hit a delay with EdgeDB, but integrating httptools deeper in it is on my immediate todo. And so I'll be closely looking at that and will also likely release uvloop for 3.9. Sorry for the delay.

**Comment by fantix** [comment] 2021-03-30 17:11
Thanks to @victoraugustolls and everyone, this is done in #56. I'll get a release out soon.

**Closed by fantix** 2021-03-30 17:11 UTC
